sudo: required
services:
  - docker

before-install:
  - docker build -t epic_varahamihira/docker_react -f Dockerfile.dev .

script:
  - docker run epic_varahamihira/docker_react npm run test -- --coverage
